import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { transform } from 'esbuild';

const config = JSON.parse(await readFile('webflow/deployment.json', 'utf8'));
const { version } = JSON.parse(await readFile('package.json', 'utf8'));
assert.equal(config.production.version, version, 'Update the deployment version together with package.json');
assert.equal(config.production.js, `https://cdn.jsdelivr.net/gh/brandvm/brandvm@${version}/dist/index.js`);
assert.equal(config.production.css, `https://cdn.jsdelivr.net/gh/brandvm/brandvm@${version}/dist/styles.css`);

async function inline(file, fn) {
  const source = await readFile(file, 'utf8');
  const { code } = await transform(`${source}\n${fn}(${JSON.stringify(config)});`, { minify: true, target: 'es2019' });
  return `<script>${code.trim()}</script>\n`;
}

const head = '<!-- Keep existing tracking, metadata, schema and inline styles. Custom CSS is in the shared Embed; custom JavaScript starts in the footer. -->\n<link rel="preconnect" href="https://cdn.jsdelivr.net" />\n';
const designer = `<!-- Shared CSS + environment Embed: place once on every page, near the top. -->
<link id="bv-css" data-bv-css rel="stylesheet" href="${config.production.css}" />
${await inline('webflow/css-config.js', 'prepareBrandVisionStyles')}`;
const footer = '<!-- Footer: the single custom JavaScript loader. Keep unrelated page and site code. -->\n' + await inline('webflow/footer-loader.js', 'loadBrandVisionScript');

await writeFile('webflow/head-assets.html', head);
await writeFile('webflow/designer-css.html', designer);
await writeFile('webflow/footer-assets.html', footer);
await writeFile('loader.html', `<!-- GENERATED by pnpm snippets. Three placements; do not paste this whole file.
Adapted from brandvm/wf-template: CSS/config in a shared Embed, JS in Footer.
The released v${version} CSS and feature bundle are unchanged. This is an
intentional integration timing/cascade change; test all three pieces together
on Webflow staging before production. No Webflow publication is automated.

Remove the previous bv-site-css head link and loadBrandVisionAssets bootstrap.
Replace the previous Designer CSS link/cleanup with piece 2. Do not retain a
second custom bundle tag. Preserve all tracking, schema, inline styles and
page/component scripts around these asset-only replacements.

Dev: pnpm dev, then ?bv-dev=1 on *.webflow.io (or the actual *.canvas.webflow.com
preview frame URL). ?bv-dev=0 exits; the choice persists per browser origin.
Designer canvas: the real CSS link shows the released stylesheet. For local
CSS, use the browser-only override documented in README.md; do not publish a
static localhost link. This avoids local-network requests from production.
-->

<!-- 1. Site settings: Head code (asset portion only). -->
${head}
<!-- 2. Shared on-canvas Embed: CSS + environment selection. -->
${designer}
<!-- 3. Site settings: Footer code, before </body>. -->
${footer}`);
