import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { transform } from 'esbuild';

const config = JSON.parse(await readFile('webflow/deployment.json', 'utf8'));
const { version } = JSON.parse(await readFile('package.json', 'utf8'));
const baseline = JSON.parse(await readFile('migration/baseline.json', 'utf8'));
assert.equal(config.production.version, version, 'Update the deployment version together with package.json');
assert.equal(config.production.js, `https://cdn.jsdelivr.net/gh/brandvm/brandvm@${version}/dist/index.js`);
assert.equal(config.production.css, `https://cdn.jsdelivr.net/gh/brandvm/brandvm@${version}/dist/styles.css`);

const loader = await readFile('webflow/assets-loader.js', 'utf8');
let code;
if (version === baseline.runtimeVersion) {
  // A different URL changes esbuild's character-frequency-based identifier
  // names. Keep the first migration's published diff strictly URL-only.
  const published = await readFile(baseline.publishedBootstrap.file, 'utf8');
  const [owner, repository] = baseline.sourceRepository.split('/');
  code = published
    .replaceAll(baseline.assets['dist/index.js'].sourceUrl, config.production.js)
    .replaceAll(baseline.assets['dist/styles.css'].sourceUrl, config.production.css)
    .replaceAll(`https://${owner}.github.io/${repository}/`, config.stagingBase);
} else {
  ({ code } = await transform(`${loader}\nloadBrandVisionAssets(${JSON.stringify(config)});`, { minify: true, target: 'es2019' }));
}
const head = `<link id="bv-site-css" rel="stylesheet" href="${config.production.css}" />\n<script>${code.trim()}</script>\n`;
const footer = '<!-- Custom JavaScript is loaded by the head bootstrap and initializes through Webflow.push. -->\n';
const designer = `<!-- Persistent Designer preview; the published head owns the active stylesheet. -->
<link data-bv-designer-css rel="stylesheet" href="${config.production.css}" />
<script>
  if (document.getElementById('bv-site-css')) {
    document.querySelectorAll('link[data-bv-designer-css]').forEach(function (link) {
      link.remove();
    });
  }
</script>
`;

await writeFile('webflow/head-assets.html', head);
await writeFile('webflow/footer-assets.html', footer);
await writeFile('webflow/designer-css.html', designer);
await writeFile('loader.html', `<!-- GENERATED by pnpm snippets. Reference only; do not paste this whole file.
Future migration: replace ONLY the custom asset URLs/snippets in their current
locations. Keep all existing tracking, metadata, schema, component markup,
breakpoint CSS, and page-specific code. No Webflow change is part of repo setup.

The loader, initialization timing, CSS order and Designer cleanup match the
currently published v1.1.0 setup. Only repository delivery addresses change.
Verify the pinned release URLs before any future source switch.
-->

<!-- 1. Site Head: replace the existing bv-site-css link and its bootstrap. -->
${head}
<!-- 2. Existing shared Embed: replace only its Designer CSS link/cleanup.
Keep the GTM noscript iframe and the menu breakpoint styles around it. -->
${designer}
<!-- 3. Site Footer: the existing setup needs no additional JS tag. -->
${footer}`);
